"""Merge the facts layer and the editorial layer into the site's tenders.json.

Option C, final step. Two source files, two owners:
  * tenders_facts.json     — machine-derived, regenerated by export_json.py
  * tenders_editorial.json — hand-authored judgment, keyed by tender_ref

This script joins them (facts is the spine; editorial attaches by tender_ref)
and writes site/src/data/tenders.json, the file the Astro site builds from.
Overwriting tenders.json is now safe: nothing original lives only there —
facts and editorial are each preserved in their own file.

Usage:
    python pipeline/merge_site_data.py [output_path]
    # default output_path = site/src/data/tenders.json
    # pass a temp path to preview without touching the live site file.

SITE-COMPATIBILITY LAYER
------------------------
The facts schema renamed/!restructured several fields the Astro pages still
read under their old names (bid_deadline, pre_bid_date, source_date, state,
city, lot, contract_model, the clean title, and the status_history shape).
Rather than ship a regression, the merge derives those aliases from the facts
so the current site renders unchanged. Each alias is commented below. The
cleaner long-term fix is to update the Astro pages to read the native field
names and then delete this layer — see the field-coverage notes in the PR.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "site" / "src" / "data"
FACTS_PATH = DATA_DIR / "tenders_facts.json"
EDITORIAL_PATH = DATA_DIR / "tenders_editorial.json"
DEFAULT_OUT = DATA_DIR / "tenders.json"

# Editorial fields attached by tender_ref. display_title is handled separately
# (it has a fallback); these are pure pass-through.
EDITORIAL_FIELDS = ("why_it_matters", "key_risks", "eligibility_summary", "notes", "tags")

# Controlled scheme value -> human display label. The site renders t.scheme
# directly (badge, field, page description, filter dropdown), so without this
# it would show 'pm_ebus_sewa' instead of 'PM e-Bus Sewa'. Same display-label
# pattern as source_type->government_portal in export_json.py. Unmapped schemes
# fall back to a title-cased best effort.
SCHEME_LABEL = {
    "pm_ebus_sewa": "PM e-Bus Sewa",
    "pm_edrive": "PM E-DRIVE",
    "fame_2": "FAME II",
    "state_funded": "State-funded",
    "smart_city": "Smart City",
    "other": "Other",
    "unknown": "Unknown",
}


def parse_json_array(value) -> list:
    """Parse a states/cities JSON-string column into a list. Defensive: already
    a list passes through; NULL/empty -> []; a bare string -> single-item list.
    """
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return value
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, list) else [parsed]
    except (json.JSONDecodeError, TypeError):
        return [value]


def reshape_status_history(history: list) -> list:
    """Map facts events (event_date/event_type/details/...) into the shape the
    tender page renders (ev.date, ev.note), keeping the provenance fields too.
    """
    out = []
    for ev in history or []:
        out.append({
            "date": ev.get("event_date"),          # site reads ev.date
            "note": ev.get("details"),             # site reads ev.note
            "event_type": ev.get("event_type"),
            "source_url": ev.get("source_url"),
            "source_key": ev.get("source_key"),
        })
    return out


def merge_record(fact: dict, editorial: dict | None) -> dict:
    ed = editorial or {}

    # Spine: every factual field as-is.
    rec = dict(fact)

    # --- states/cities: JSON strings -> arrays (per spec) ---
    states = parse_json_array(fact.get("states"))
    cities = parse_json_array(fact.get("cities"))
    rec["states"] = states
    rec["cities"] = cities

    # --- editorial attach ---
    display_title = ed.get("display_title") or fact.get("title")
    rec["display_title"] = display_title
    for f in EDITORIAL_FIELDS:
        rec[f] = ed.get(f) if f in ed else (None if f != "tags" else [])

    # --- status_history: reshape to the site's {date, note, ...} shape ---
    rec["status_history"] = reshape_status_history(fact.get("status_history"))

    # ----------------------------------------------------------------------
    # SITE-COMPATIBILITY ALIASES (see module docstring). Each line keeps a
    # current Astro page working without a source change. Derived only —
    # no invented data.
    # ----------------------------------------------------------------------
    # Clean title: site renders t.title; the clean title now lives in editorial.
    rec["title"] = display_title
    # Singular state/city the detail page + search read (from the arrays).
    rec["state"] = ", ".join(states) if states else None
    rec["city"] = ", ".join(cities) if cities else None
    # Lot label under the old key the detail page + search read.
    rec["lot"] = fact.get("lot_label")
    # Date fields the pages read under v1 names (site already ?? to *_due/etc).
    rec["bid_deadline"] = fact.get("bid_due_date")
    rec["pre_bid_date"] = fact.get("prebid_date")
    rec["source_date"] = fact.get("issue_date")
    # Contract model alias (also feeds the contract-type filter dropdown).
    rec["contract_model"] = fact.get("procurement_model")
    # Bus type: the page reads t.bus_type; the only value we hold is the
    # bus_length_m column (carries 'standard' for these rows). Loose mapping —
    # flagged for cleanup when the site moves to native field names.
    rec["bus_type"] = fact.get("bus_length_m")
    # Scheme display label (site renders t.scheme raw). Keep the controlled
    # value available in tenders_facts.json; show the label on the site.
    fact_scheme = fact.get("scheme")
    rec["scheme"] = SCHEME_LABEL.get(fact_scheme, fact_scheme)

    return rec


def main() -> None:
    facts = json.loads(FACTS_PATH.read_text(encoding="utf-8"))
    editorial = json.loads(EDITORIAL_PATH.read_text(encoding="utf-8"))

    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT

    merged = []
    unmatched = []
    for fact in facts:
        ref = fact.get("tender_ref")
        ed = editorial.get(ref)
        if ed is None:
            unmatched.append(ref)
        merged.append(merge_record(fact, ed))

    out_path.write_text(
        json.dumps(merged, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {out_path}: {len(merged)} tenders")
    if unmatched:
        print(f"WARNING: {len(unmatched)} tender(s) had no editorial match: {unmatched}")
    # Surface editorial entries with no matching fact (orphaned editorial).
    fact_refs = {f.get("tender_ref") for f in facts}
    orphans = [r for r in editorial if r not in fact_refs]
    if orphans:
        print(f"WARNING: {len(orphans)} editorial entr(ies) matched no fact: {orphans}")


if __name__ == "__main__":
    main()
