"""Merge the facts layer and the editorial layer into the site's tenders.json.

Option C, final step. Two source files, two owners:
  * tenders_facts.json     — machine-derived, regenerated by export_json.py
  * tenders_editorial.json — hand-authored judgment, keyed by tender_ref

This script joins them (facts is the spine; editorial attaches by tender_ref)
and writes site/src/data/tenders.json, the file the Astro site builds from.
Overwriting tenders.json is now safe: nothing original lives only there —
facts and editorial are each preserved in their own file.

Usage:
    python pipeline/merge_site_data.py [output_path]
    # default output_path = site/src/data/tenders.json
    # pass a temp path to preview without touching the live site file.

NO COMPATIBILITY LAYER
----------------------
The Astro pages read native field names directly (bid_due_date, prebid_date,
issue_date, states[], cities[], lot_label, procurement_model, bus_length_m,
scheme, and the native status_history shape). The old alias block that
translated those to v1 names was removed once the pages were migrated. This
merge now does only what it must: copy the facts spine, parse states/cities
into arrays, attach editorial (display_title + judgment fields), and guarantee
a lots[] array. Scheme display labels live on the site (site/src/lib/labels.ts).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "site" / "src" / "data"
FACTS_PATH = DATA_DIR / "tenders_facts.json"
EDITORIAL_PATH = DATA_DIR / "tenders_editorial.json"
DEFAULT_OUT = DATA_DIR / "tenders.json"

# Editorial fields attached by tender_ref. display_title is handled separately
# (it has a fallback); these are pure pass-through.
EDITORIAL_FIELDS = ("why_it_matters", "key_risks", "eligibility_summary", "notes", "tags")


def parse_json_array(value) -> list:
    """Parse a states/cities JSON-string column into a list. Defensive: already
    a list passes through; NULL/empty -> []; a bare string -> single-item list.
    """
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return value
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, list) else [parsed]
    except (json.JSONDecodeError, TypeError):
        return [value]


def merge_record(fact: dict, editorial: dict | None) -> dict:
    ed = editorial or {}

    # Spine: every factual field as-is.
    rec = dict(fact)

    # --- states/cities: JSON strings -> arrays (per spec) ---
    states = parse_json_array(fact.get("states"))
    cities = parse_json_array(fact.get("cities"))
    rec["states"] = states
    rec["cities"] = cities

    # --- editorial attach ---
    display_title = ed.get("display_title") or fact.get("title")
    rec["display_title"] = display_title
    for f in EDITORIAL_FIELDS:
        rec[f] = ed.get(f) if f in ed else (None if f != "tags" else [])

    # City-lot decomposition: ensure the plural array is always present (the
    # spine already copies it from facts; default [] for tenders with none).
    rec["lots"] = fact.get("lots", [])

    # status_history, scheme, dates, lot_label, bus_length_m, procurement_model,
    # and the native title pass through unchanged from the facts spine — the
    # Astro pages now read those native field names directly (scheme labels are
    # applied client-side via site/src/lib/labels.ts). No compatibility aliases.
    return rec


def main() -> None:
    facts = json.loads(FACTS_PATH.read_text(encoding="utf-8"))
    editorial = json.loads(EDITORIAL_PATH.read_text(encoding="utf-8"))

    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT

    merged = []
    unmatched = []
    for fact in facts:
        ref = fact.get("tender_ref")
        ed = editorial.get(ref)
        if ed is None:
            unmatched.append(ref)
        merged.append(merge_record(fact, ed))

    out_path.write_text(
        json.dumps(merged, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {out_path}: {len(merged)} tenders")
    if unmatched:
        print(f"WARNING: {len(unmatched)} tender(s) had no editorial match: {unmatched}")
    # Surface editorial entries with no matching fact (orphaned editorial).
    fact_refs = {f.get("tender_ref") for f in facts}
    orphans = [r for r in editorial if r not in fact_refs]
    if orphans:
        print(f"WARNING: {len(orphans)} editorial entr(ies) matched no fact: {orphans}")


if __name__ == "__main__":
    main()
